name: CI
on:
  push:
  workflow_dispatch:
env:
  CI: true

jobs:
  db:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - name: Copy ci env vars
        run: cp .env.example .env
      - uses: supabase/setup-cli@v1
        with:
          version: 1.22.3
      - name: Start supabase
        run: supabase start
      - name: Test supabase
        run: supabase test db

  # unit:
  #     runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel previous runs
  #       uses: styfle/cancel-workflow-action@0.11.0
  #     - uses: actions/checkout@v3
  #     - name: Copy ci env vars
  #       run: cp .env.example .env
  #     - uses: pnpm/action-setup@v2
  #       with:
  #         version: 7
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: "pnpm"
  #     - name: Install dependencies
  #       run: pnpm install
  #     - name: Build
  #       run: pnpm build
  #     - name: Test
  #       run: pnpm test
        
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - name: Copy ci env vars
        run: cp .env.example .env
      - uses: supabase/setup-cli@v1
        with:
          version: 1.22.3
      - name: Start supabase
        run: supabase start
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Install playwright browsers
        run: pnpm dlx playwright install --with-deps
      - name: Build
        run: pnpm build
      - name: Run playwright tests
        run: pnpm dlx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
