name: PGTap Tests
on:
  pull_request:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Supabase Start
        run: supabase start
      - name: Run Tests
        run: supabase test db
