name: Production Release
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  db-push-job:
    name: Database Push Job
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PROD_SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.PROD_SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.22.3
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
