name: Staging Release
on:
  push:
    branches: [dev]
  workflow_dispatch:
jobs:
  db-test-job:
    name: Database Test Job
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.22.3
      - name: Start supabase
        run: supabase start
      - name: Test supabase
        run: supabase test db
  db-push-job:
    name: Database Push Job
    needs: db-test-job
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_SUPABASE_PROJECT_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.22.3
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db push
