name: Staging Database Push

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_STAGING_DB_PASSWORD }}
      PROJECT_ID: ypkjlvughauqpeczcigv

    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.22.3
      - run: supabase link --project-ref $PROJECT_ID
      - run: supabase db push